/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonSalir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonListaPedido = new javax.swing.JButton();
        botonCrearUsuario = new javax.swing.JButton();
        botonListaTerceros = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonListaVentas = new javax.swing.JButton();
        botonListaUsuarios = new javax.swing.JButton();
        botonCrearTerceros = new javax.swing.JButton();
        BotonListaProducto = new javax.swing.JButton();
        BotonCrearProducto = new javax.swing.JButton();
        botonCrearPedido = new javax.swing.JButton();
        BotonVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 251, 252));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(4, 137, 212));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Menú Principal");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        jLabel1.setBackground(new java.awt.Color(34, 43, 56));
        jLabel1.setForeground(new java.awt.Color(34, 43, 56));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 53));

        botonSalir1.setBackground(new java.awt.Color(242, 242, 242));
        botonSalir1.setText("Salir");
        getContentPane().add(botonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel2.setBackground(new java.awt.Color(69, 78, 91));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 80, 470));

        botonListaPedido.setBackground(new java.awt.Color(68, 114, 196));
        botonListaPedido.setForeground(new java.awt.Color(255, 255, 255));
        botonListaPedido.setText("Lista Pedido");
        getContentPane().add(botonListaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 120, 70));

        botonCrearUsuario.setBackground(new java.awt.Color(112, 173, 71));
        botonCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearUsuario.setText("Crear Usuario");
        botonCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 70));

        botonListaTerceros.setBackground(new java.awt.Color(68, 114, 196));
        botonListaTerceros.setForeground(new java.awt.Color(255, 255, 255));
        botonListaTerceros.setText("Lista Terceros");
        botonListaTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaTercerosActionPerformed(evt);
            }
        });
        getContentPane().add(botonListaTerceros, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 70));

        BotonSalir.setBackground(new java.awt.Color(255, 0, 0));
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("<html>Salir</html>");
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 120, 90));

        BotonListaVentas.setBackground(new java.awt.Color(68, 114, 196));
        BotonListaVentas.setForeground(new java.awt.Color(255, 255, 255));
        BotonListaVentas.setText("Lista Ventas");
        getContentPane().add(BotonListaVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 70));

        botonListaUsuarios.setBackground(new java.awt.Color(112, 173, 71));
        botonListaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonListaUsuarios.setText("Lista Usuarios");
        botonListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(botonListaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 70));

        botonCrearTerceros.setBackground(new java.awt.Color(68, 114, 196));
        botonCrearTerceros.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearTerceros.setText("<html>Crear Terceros</html>");
        getContentPane().add(botonCrearTerceros, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 120, 70));

        BotonListaProducto.setBackground(new java.awt.Color(222, 171, 83));
        BotonListaProducto.setForeground(new java.awt.Color(255, 255, 255));
        BotonListaProducto.setText("Lista Productos");
        BotonListaProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        getContentPane().add(BotonListaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 70));

        BotonCrearProducto.setBackground(new java.awt.Color(222, 171, 83));
        BotonCrearProducto.setForeground(new java.awt.Color(255, 255, 255));
        BotonCrearProducto.setText("Crear Producto");
        getContentPane().add(BotonCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, 70));

        botonCrearPedido.setBackground(new java.awt.Color(68, 114, 196));
        botonCrearPedido.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearPedido.setText("Crear Pedido");
        getContentPane().add(botonCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, 70));

        BotonVentas.setBackground(new java.awt.Color(68, 114, 196));
        BotonVentas.setForeground(new java.awt.Color(255, 255, 255));
        BotonVentas.setText("<html>Ventas</html>");
        getContentPane().add(BotonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 120, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonListaUsuariosActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonListaTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaTercerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonListaTercerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonCrearProducto;
    public javax.swing.JButton BotonListaProducto;
    public javax.swing.JButton BotonListaVentas;
    public javax.swing.JButton BotonSalir;
    public javax.swing.JButton BotonVentas;
    public javax.swing.JButton botonCrearPedido;
    public javax.swing.JButton botonCrearTerceros;
    public javax.swing.JButton botonCrearUsuario;
    public javax.swing.JButton botonListaPedido;
    public javax.swing.JButton botonListaTerceros;
    public javax.swing.JButton botonListaUsuarios;
    public javax.swing.JButton botonSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
